include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = libhidsupport
libhidsupport_FILES = client.c
libhidsupport_INSTALL_PATH = /usr/local/lib
libhidsupport_FRAMEWORKS = CoreFoundation
include $(FW_MAKEDIR)/library.mk
