include theos/makefiles/common.mk

TWEAK_NAME = hidspringboard
hidspringboard_FILES = Tweak.xm
hidspringboard_FRAMEWORKS = UIKit
hidspringboard_PRIVATE_FRAMEWORKS = QuartzCore GraphicsServices
include $(THEOS_MAKE_PATH)/tweak.mk
