include theos/makefiles/common.mk

TOOL_NAME = hidsupporttest
hidsupporttest_FILES = main.c
hidsupporttest_CFLAGS = -I..
hidsupporttest_LDFLAGS = -L../libhidsupport/obj -lhidsupport

include $(THEOS_MAKE_PATH)/tool.mk
